name: Web App CI
run-name: ${{ github.actor }} - Web App Haproxy CI

on:
  push:
    branches:
      - develop
  pull_request:
    types: 
      - opened

env:
  VERSION: 1.0

jobs:
  Haproxy:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Haproxy
        run: |
          cd ${{ github.workspace }}/haproxy
          docker build -t haproxy -f Dockerfile .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Haproxy image
        run: |
          docker tag haproxy:latest ghcr.io/patrykk/haproxy:${{ env.VERSION }}
          docker push ghcr.io/patrykk/haproxy:${{ env.VERSION }}
  
  webapp:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Webapp
        run: |
          cd ${{ github.workspace }}/web
          docker build -t webapp -f Dockerfile .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Webapp image
        run: |
          docker tag webapp:latest ghcr.io/patrykk/webapp:${{ env.VERSION }}
          docker push ghcr.io/patrykk/webapp:${{ env.VERSION }}
